version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php-dev
    volumes:
      - ./PHP:/var/www/html/PHP
      - ./laravel:/var/www/html/laravel
    networks:
      - dev-network

  nginx:
    image: nginx:alpine
    container_name: nginx-dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./PHP:/var/www/html/PHP
      - ./laravel:/var/www/html/laravel
    depends_on:
      - php
    networks:
      - dev-network

  mysql:
    image: mysql:8.0
    container_name: mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: developer
      MYSQL_PASSWORD: developer
    ports:
      - "3308:3306"
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - mysql-data:/var/lib/mysql
    networks:
      - dev-network

  postgres:
    image: postgres:13
    container_name: postgres-dev
    environment:
      POSTGRES_DB: laravel_pg
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dev-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-dev
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

volumes:
  mysql-data:
  postgres-data: