services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.universal
    volumes:
      - ./practicasConceptos:/var/www/html
    ports:
      - "90:80"
      - "443:443"
    environment:
      - COMPOSER_MEMORY_LIMIT=-1

  mysql:
    image: mysql:8.0
    container_name: mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev_database
      MYSQL_USER: developer
      MYSQL_PASSWORD: developer
    command:
      - --default-authentication-plugin=mysql_native_password
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  postgresql:
    image: postgres:15
    container_name: postgres-dev
    environment:
      POSTGRES_DB: dev_database
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-dev
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql

  node:
    image: node:20
    volumes:
      - ./practicasConceptos:/app
    working_dir: /app
    command: tail -f /dev/null
   
volumes:
  mysql-data:
  postgres-data: